### ISSUE TITLE
老哥 为啥会报错

### ISSUE THREAD

**Issue by sevendian** [zhutougg/LandrayDES#1]
Exception in thread "main" javax.crypto.BadPaddingException: pad block corrupted
        at org.bouncycastle.jce.provider.JCEBlockCipher.engineDoFinal(Unknown Source)
        at javax.crypto.Cipher.doFinal(Cipher.java:2168)
        at com.zhutougg.LandrayDES.DESEncrypt.decrypt(DESEncrypt.java:75)
        at com.zhutougg.LandrayDES.DESEncrypt.decryptString(DESEncrypt.java:88)
        at com.zhutougg.LandrayDES.DESEncrypt.main(DESEncrypt.java:123)

**Comment by B3i4hu** [comment]
同问
